### ISSUE TITLE
decide type for metadata value

### ISSUE THREAD

**Issue by weissi** [weissi/swift-server-logging-api-proposal#5]
--> 
https://forums.swift.org/t/server-logging-api/18834/13

**Comment by ktoso** [comment]
I second that we should not force the values to be `String` since it forces evaluating things that should not really have to be e.g. due to a log level which would stop them from being logged anyway.

Some discussion for this topic inside the PR I made here: https://github.com/weissi/swift-server-logging-api-proposal/pull/6

**Comment by weissi** [comment]
done, landed on supporting strings, arrays and (nested) dictionaries thereof
